GET http://localhost:3000/api/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTc0NDM3MTUyMywiZXhwIjoxNzQ0NDU3OTIzfQ.GLP046PX6Nc0tgRmVNrlgjna2K2jE1a6BaVheXMfuxY
# Content-Type: application/json

# {
#   "email": "user3@gmail.com",
#   "password": "Password2024"
# }