delete http://localhost:3000/api/admins/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjozLCJpYXQiOjE3NDQ0MDU3NDAsImV4cCI6MTc0NDQ5MjE0MH0.yrc87W-mhDc2ph6GUK0W_k4g1rYmHogrNkjZ9afVK04
# Content-Type: application/json

# {
#   "email": "recruter111000@gmail.com",
#    "name": "Recruiterfirst"
# }